name: Analyze News & Export CSV

permissions:
  contents: write

on:
  schedule:
    - cron: '30 7 * * *'  # Daily at 07:30 UTC
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install textblob
          python -m textblob.download_corpora

      - name: Run analysis script
        run: python scripts/analyze_news.py

      - name: Commit output files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/enriched_news.*
          git add -u data/
          git commit -m "Daily news analysis output on $(date -u +'%Y-%m-%d')" || echo "No changes to commit"

      - name: Push to repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
