name: 🧹 Cleanup old news JSON

permissions:
  contents: write

on:
  schedule:
    - cron:  '5 0 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Run cleanup script
        run: bash scripts/cleanup_old_news.sh

      - name: Commit & push deletions
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data
            git commit -m "ci: remove per-day JSON older than 7 days"
            git push
          else
            echo "Nothing to clean up."
          fi
