name: Populate platforms_mentioned

on:
  schedule:
    - cron: "15 3 * * *"      # daily at 03:15 UTC
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - run: pip install pandas

      - name: Tag news articles
        run: python scripts/tag_platforms.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add data/news_*.json
          git commit -m "ci: auto-tag platforms" || echo "Nothing to commit"
          git push
