name: Populate platforms_mentioned

permissions:
  contents: write            # let GITHUB_TOKEN push commits

on:
  schedule:
    - cron: "15 3 * * *"     # daily at 03:15 UTC
  workflow_dispatch:         # allow manual run from the Actions tab

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      # ────────────────────────────────────────────────────────────────
      # 1. Check out the repository
      # ────────────────────────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4

      # ────────────────────────────────────────────────────────────────
      # 2. Python environment
      # ────────────────────────────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"      # no pip-cache → avoids requirements-file warning

      - name: Install dependencies
        run: pip install pandas

      # ────────────────────────────────────────────────────────────────
      # 3. Populate `platforms_mentioned`
      # ────────────────────────────────────────────────────────────────
      - name: Tag news articles
        run: python scripts/tag_platforms.py

      # ────────────────────────────────────────────────────────────────
      # 4. Build daily company digest (optional utility file)
      # ────────────────────────────────────────────────────────────────
      - name: Build daily company digest
        run: python scripts/build_daily_company_digest.py

      # ────────────────────────────────────────────────────────────────
      # 5. Commit & push any changes
      # ────────────────────────────────────────────────────────────────
      - name: Commit updated JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # ▼ stage the new digest file in addition to the daily news files
          git add data/news_*.json data/news_filtered_for_companies_of_interest.json

          # commit only if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "ci: auto-tag platforms & refresh company digest"
            git push
          else
            echo "No changes to commit"
          fi
